server:
  port: 9093
dubbo:
  application:
    name: user
  registry:
    address: zookeeper://120.26.176.124:2181
    consumer:
      retrices: 10
spring:
  redis:
    host: 120.26.176.124
    port: 6379
    password: admin123
    database: 12
  rabbitmq:
    virtual-host: admin
    username: xiaoming
    password: 123456
    host: 120.26.176.124
    port: 5672
logging:
  level:
    com.qf.mapper: debug